# Generated by Django 3.0.6 on 2020-05-20 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('N', 'New'), ('I', 'In Progress'), ('D', 'Done'), ('I', 'Invalid')], default='N', max_length=1)),
                ('userassigned', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userassigned', to=settings.AUTH_USER_MODEL)),
                ('usercompleted', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='usercompleted', to=settings.AUTH_USER_MODEL)),
                ('usersubmited', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='usersubmitted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
