# Generated by Django 3.0.6 on 2020-05-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0007_auto_20200520_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('P', 'In Progress'), ('D', 'Done'), ('N', 'Invalid')], default='N', max_length=1),
        ),
    ]
