# Generated by Django 3.0.6 on 2020-05-20 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0009_auto_20200520_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='tickets',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bug_tracker.Ticket'),
        ),
    ]
